// <auto-generated />
namespace AntiCorruptionManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_replace_SubwingstoSajeka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_replace_SubwingstoSajeka));
        
        string IMigrationMetadata.Id
        {
            get { return "201712200516271_update_replace_SubwingstoSajeka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
